//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.JbigViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.JbigViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutMenuItemHeader {
            get {
                return ResourceManager.GetString("AboutMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon BUILDLet_JbigViewer {
            get {
                object obj = ResourceManager.GetObject("BUILDLet_JbigViewer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseMenuItemHeader {
            get {
                return ResourceManager.GetString("CloseMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitMenuItemHeader {
            get {
                return ResourceManager.GetString("ExitMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenuItemHeader {
            get {
                return ResourceManager.GetString("FileMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpMenuItemHeader {
            get {
                return ResourceManager.GetString("HelpMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageMenuItemHeader {
            get {
                return ResourceManager.GetString("ImageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Next Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextPageMenuItemHeader {
            get {
                return ResourceManager.GetString("NextPageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Previous Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviousPageMenuItemHeader {
            get {
                return ResourceManager.GetString("PreviousPageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviousPageToolTip {
            get {
                return ResourceManager.GetString("PreviousPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove unexpected data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveUnexpectedDataMenuItemHeader {
            get {
                return ResourceManager.GetString("RemoveUnexpectedDataMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Same as original image size (100%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SameAsOriginalImageSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("SameAsOriginalImageSizeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveAsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewMenuItemHeader {
            get {
                return ResourceManager.GetString("ViewMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Zoom In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomInMenuItemHeader {
            get {
                return ResourceManager.GetString("ZoomInMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoo_m Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomOutMenuItemHeader {
            get {
                return ResourceManager.GetString("ZoomOutMenuItemHeader", resourceCulture);
            }
        }
    }
}
