//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.JBIG.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.JBIG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to run &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jbgtopbm.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_JbgToPbm_EXE {
            get {
                return ResourceManager.GetString("FileName_JbgToPbm_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pnmtopng.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_PnmToPng_EXE {
            get {
                return ResourceManager.GetString("FileName_PnmToPng_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pnmtotiff.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_PnmToTiff_EXE {
            get {
                return ResourceManager.GetString("FileName_PnmToTiff_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ppmtobmp.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_PpmToBmp_EXE {
            get {
                return ResourceManager.GetString("FileName_PpmToBmp_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ppmtogif.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_PpmToGif_EXE {
            get {
                return ResourceManager.GetString("FileName_PpmToGif_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ppmtojpeg.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileName_PpmToJpeg_EXE {
            get {
                return ResourceManager.GetString("FileName_PpmToJpeg_EXE", resourceCulture);
            }
        }
    }
}
